/**
 * This file was generated by the JPA Modeler
 */
package com.sgd.hermes.model;

import java.io.Serializable;
import java.sql.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * @author jkelsy
 */
@Entity
@Table(name = "detalle_archivo_central")
public class DetalleArchivoCentral implements Serializable {

    @Column(name = "detalle_ac_id", unique = true)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Basic
    private Date fecha;

    @ManyToOne(targetEntity = Usuario.class)
    @JoinColumn(name = "CREADO_POR_ID")
    private Usuario creadoPor;

    @ManyToOne(targetEntity = ArchivoCentral.class)
    @JoinColumn(name = "ARCHIVO_CENTRAL_ID")
    private ArchivoCentral archivoCentral;

    @ManyToOne(targetEntity = TipoDocumental.class)
    @JoinColumn(name = "TP_DOCUMENTAL_ID")
    private TipoDocumental tipoDocumental;

    @ManyToOne(targetEntity = Archivo.class)
    @JoinColumn(name = "ARCHIVO_ID")
    private Archivo archivo;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public Usuario getCreadoPor() {
        return this.creadoPor;
    }

    public void setCreadoPor(Usuario creadoPor) {
        this.creadoPor = creadoPor;
    }

    public ArchivoCentral getArchivoCentral() {
        return this.archivoCentral;
    }

    public void setArchivoCentral(ArchivoCentral archivoCentral) {
        this.archivoCentral = archivoCentral;
    }

    public TipoDocumental getTipoDocumental() {
        return this.tipoDocumental;
    }

    public void setTipoDocumental(TipoDocumental tipoDocumental) {
        this.tipoDocumental = tipoDocumental;
    }

    public Archivo getArchivo() {
        return this.archivo;
    }

    public void setArchivo(Archivo archivo) {
        this.archivo = archivo;
    }

}
