/**
 * This file was generated by the JPA Modeler
 */ 

package com.sgd.hermes.model;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * @author  jdmp
 */

@Entity
@Table(name="poblado")
@NamedQuery(name="Poblado.findAllByMunicipio",query="Select e from Poblado e WHERE e.municipio.id = :municipio_id")
public class Poblado { 

    @Column(name="pob_id",unique=true)
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    private Long id;

    @Column(name="pob_codigo")
    @Basic
    private String codigo;

    @Column(name="pob_nombre")
    @Basic
    private String nombre;

    @ManyToOne(targetEntity = Municipio.class)
    @JoinColumn(name="MUNICIPIO_ID")
    private Municipio municipio;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Municipio getMunicipio() {
        return this.municipio;
    }

    public void setMunicipio(Municipio municipio) {
        this.municipio = municipio;
    }

}
