/**
 * This file was generated by the JPA Modeler
 */ 

package com.sgd.hermes.model;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * @author  jdmp
 */

@Entity
@Table(name="sub_serie")
@NamedQueries({@NamedQuery(name="SubSerie.findByCodigo",query="Select s from SubSerie s where s.codigo=:codigo"),@NamedQuery(name="SubSerie.findAllBySerie",query="Select ss from SubSerie ss where ss.serie.id =:serie_id ")})
public class SubSerie { 

    @Column(name="sub_serie_id")
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    private Long id;

    @Column(name="sub_serie_codigo")
    @Basic
    private String codigo;

    @Column(name="sub_serie_descripcion")
    @Basic
    private String descripcion;

    @ManyToOne(targetEntity = Serie.class)
    @JoinColumn(name="SERIE_ID")
    private Serie serie;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Serie getSerie() {
        return this.serie;
    }

    public void setSerie(Serie serie) {
        this.serie = serie;
    }

}
