/**
 * This file was generated by the JPA Modeler
 */
package com.sgd.hermes.model;

import java.lang.reflect.Field;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import org.primefaces.util.BeanUtils;

/**
 * @author jdmp
 */
@Entity
@Table(name = "tabla_retencion_documental")
@NamedQuery(name = "TablaRetencionDocumental.findByEmpresa", query = "Select e from TablaRetencionDocumental e where e.centroCosto.empresa.id = :empresa_id")
public class TablaRetencionDocumental {

    @Column(name = "trd_id", unique = true)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "trd_descripcion")
    @Basic
    private String descripcion;

    @Column(name = "trd_se_conserva")
    @Basic
    private Boolean seConserva;

    @Column(name = "trd_en_digital")
    @Basic
    private Boolean enDigital;

    @Column(name = "trd_se_elimina")
    @Basic
    private Boolean seElimina;

    @Column(name = "trd_en_fisico")
    @Basic
    private Boolean enFisico;

    @Column(name = "trd_en_micro")
    @Basic
    private Boolean enMicro;

    @Column(name = "trd_seleccion")
    @Basic
    private Boolean seleccion;

    @ManyToOne(targetEntity = CentroCosto.class)
    @JoinColumn(name = "CCOSTO_ID")
    private CentroCosto centroCosto;

    @ManyToOne(targetEntity = SubSerie.class)
    @JoinColumn(name = "SUB_SERIE_ID")
    private SubSerie subSerie;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Boolean getSeConserva() {
        return this.seConserva;
    }

    public void setSeConserva(Boolean seConserva) {
        this.seConserva = seConserva;
    }

    public Boolean getEnDigital() {
        return this.enDigital;
    }

    public void setEnDigital(Boolean enDigital) {
        this.enDigital = enDigital;
    }

    public Boolean getSeElimina() {
        return this.seElimina;
    }

    public void setSeElimina(Boolean seElimina) {
        this.seElimina = seElimina;
    }

    public Boolean getEnFisico() {
        return this.enFisico;
    }

    public void setEnFisico(Boolean enFisico) {
        this.enFisico = enFisico;
    }

    public Boolean getEnMicro() {
        return this.enMicro;
    }

    public void setEnMicro(Boolean enMicro) {
        this.enMicro = enMicro;
    }

    public Boolean getSeleccion() {
        return this.seleccion;
    }

    public void setSeleccion(Boolean seleccion) {
        this.seleccion = seleccion;
    }

    public CentroCosto getCentroCosto() {
        return this.centroCosto;
    }

    public void setCentroCosto(CentroCosto centroCosto) {
        this.centroCosto = centroCosto;
    }

    public SubSerie getSubSerie() {
        return this.subSerie;
    }

    public void setSubSerie(SubSerie subSerie) {
        this.subSerie = subSerie;
    }


}
