/**
 * This file was generated by the JPA Modeler
 */
package com.sgd.hermes.model;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * @author jdmp
 */
@Entity
@Table(name = "tabla_retencion_documental")
public class TablaRetencionDocumental implements Serializable {

    @Column(name = "trd_id", unique = true)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "trd_se_conserva")
    @Basic
    private Boolean seConserva;

    @Column(name = "trd_en_digital")
    @Basic
    private Boolean enDigital;

    @Column(name = "trd_se_elimina")
    @Basic
    private Boolean seElimina;

    @Column(name = "trd_en_fisico")
    @Basic
    private Boolean enFisico;

    @Column(name = "trd_en_micro")
    @Basic
    private Boolean enMicro;

    @Column(name = "trd_descrpcion")
    @Basic
    private String descrpcion;

    @Column(name = "trd_seleccion")
    @Basic
    private Boolean seleccion;

    @ManyToOne(targetEntity = Dependencia.class)
    @JoinColumn(name = "DEPEN_ID")
    private Dependencia dependencia;

    @ManyToOne(targetEntity = SubSerie.class)
    @JoinColumn(name = "SUB_SERIE_ID")
    private SubSerie subSerie;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Boolean isSeConserva() {
        return this.seConserva;
    }

    public void setSeConserva(Boolean seConserva) {
        this.seConserva = seConserva;
    }

    public Boolean isEnDigital() {
        return this.enDigital;
    }

    public void setEnDigital(Boolean enDigital) {
        this.enDigital = enDigital;
    }

    public Boolean isSeElimina() {
        return this.seElimina;
    }

    public void setSeElimina(Boolean seElimina) {
        this.seElimina = seElimina;
    }

    public Boolean isEnFisico() {
        return this.enFisico;
    }

    public void setEnFisico(Boolean enFisico) {
        this.enFisico = enFisico;
    }

    public Boolean isEnMicro() {
        return this.enMicro;
    }

    public void setEnMicro(Boolean enMicro) {
        this.enMicro = enMicro;
    }

    public String getDescrpcion() {
        return this.descrpcion;
    }

    public void setDescrpcion(String descrpcion) {
        this.descrpcion = descrpcion;
    }

    public Boolean isSeleccion() {
        return this.seleccion;
    }

    public void setSeleccion(Boolean seleccion) {
        this.seleccion = seleccion;
    }

    public Dependencia getDependencia() {
        return this.dependencia;
    }

    public void setDependencia(Dependencia dependencia) {
        this.dependencia = dependencia;
    }

    public SubSerie getSubSerie() {
        return this.subSerie;
    }

    public void setSubSerie(SubSerie subSerie) {
        this.subSerie = subSerie;
    }

}
