/**
 * This file was generated by the JPA Modeler
 */
package com.sgd.hermes.model;

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * @author jkelsy
 */
@Entity
@Table(name = "trd_tipo_documental")
public class TRDTipoDocumental implements Serializable {

    @Column(unique = true)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(targetEntity = TablaRetencionDocumental.class)
    @JoinColumn(name = "TRD_ID")
    private TablaRetencionDocumental tablaRetencionDocumental;

    @ManyToOne(targetEntity = TipoDocumental.class)
    @JoinColumn(name = "TIPO_DOCUMENTAL_ID")
    private TipoDocumental tipoDocumental;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public TablaRetencionDocumental getTablaRetencionDocumental() {
        return this.tablaRetencionDocumental;
    }

    public void setTablaRetencionDocumental(TablaRetencionDocumental tablaRetencionDocumental) {
        this.tablaRetencionDocumental = tablaRetencionDocumental;
    }

    public TipoDocumental getTipoDocumental() {
        return this.tipoDocumental;
    }

    public void setTipoDocumental(TipoDocumental tipoDocumental) {
        this.tipoDocumental = tipoDocumental;
    }

}
