/**
 * This file was generated by the JPA Modeler
 */ 

package com.sgd.hermes.model;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * @author  jdmp
 */

@Entity
@Table(name="trd_tipo_documental")
@NamedQueries({@NamedQuery(name="TRDTipoDocumental.findAllByTrd",query="Select e from TRDTipoDocumental e where tablaRetencionDocumental.id =:trd_id"),@NamedQuery(name="TRDTipoDocumental.findAllByTrdAndTipoDocumental",query="Select e from TRDTipoDocumental e where tablaRetencionDocumental.id =:trd_id and tipoDocumental.id =:tipo_documental_id")})
public class TRDTipoDocumental { 

    @Column(unique=true)
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    private Long id;

    @Basic
    private boolean tieneArchivo;

    @ManyToOne(targetEntity = TablaRetencionDocumental.class)
    @JoinColumn(name="TRD_ID")
    private TablaRetencionDocumental tablaRetencionDocumental;

    @ManyToOne(targetEntity = TipoDocumental.class)
    @JoinColumn(name="TIPO_DOCUMENTAL_ID")
    private TipoDocumental tipoDocumental;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public boolean isTieneArchivo() {
        return this.tieneArchivo;
    }

    public void setTieneArchivo(boolean tieneArchivo) {
        this.tieneArchivo = tieneArchivo;
    }

    public TablaRetencionDocumental getTablaRetencionDocumental() {
        return this.tablaRetencionDocumental;
    }

    public void setTablaRetencionDocumental(TablaRetencionDocumental tablaRetencionDocumental) {
        this.tablaRetencionDocumental = tablaRetencionDocumental;
    }

    public TipoDocumental getTipoDocumental() {
        return this.tipoDocumental;
    }

    public void setTipoDocumental(TipoDocumental tipoDocumental) {
        this.tipoDocumental = tipoDocumental;
    }

}
